### ISSUE TITLE
Undefined property: User::$field_photo

### ISSUE THREAD

**Issue by domaingood** [backdrop-contrib/borg#3] opened 2019-10-18 13:01 UTC
Notice: Undefined property: User::$field_photo in borg_preprocess_node() (line 237 of /themes/borg/template.php).

**Comment by ghost** [comment] 2019-11-15 07:37
This is a duplicate of https://github.com/backdrop-contrib/borg/issues/1

**Comment by jenlampton** [comment] 2019-12-24 00:50
closing as dupe.

**Closed as completed by jenlampton** 2019-12-24 00:50 UTC
Labels: duplicate
